### ISSUE TITLE
<label> hover has a clickable link cursor

### ISSUE THREAD

**Issue by LRagji** [PredixDev/px-forms-design#12]
If i use the following code  as mentioned on predix ui site `<label for="input1">Input Label</label>` and when i hover over it, it turns the mouse pointer into clickable cursor which makes the user feel its a clickable link..

## Expected behavior 
Mouse pointer should not change from normal arrow pointer
## Actual behavior:
Mouse pointer changes to clickable pointer

**Comment by randyaskin** [comment]
This is by design, since form labels are interactive/clickable elements. Clicking on an input label causes focus to be placed inside the input. Clicking on a label for a checkbox or radio button toggles the state of the element.

**Comment by LRagji** [comment]
I understand this is by design and a useful feature, but would it make sense to have a prop exposed to enable/disable this feature, the context where i am coming from is when the user doesn't has a editable form(cause of permission etc) in that case the textbox is not visible but the label is still clickable........

**Comment by randyaskin** [comment]
I'm looking into this. The labels for checkboxes  / radio buttons do change their cursor to not-allowed when the associated field is disabled, but that's because the `<label>` element _follows_ the corresponding `<input>` element. CSS famously lacks a previous sibling selector, but I can change the demo to suggest that both the input and label should be disabled, causing the label to accurately reflect that the field is disabled.

**Comment by randyaskin** [comment]
The `disabled` attribute doesn't apply to `<label>` elements, but if you add the class "disabled" to your label element, the cursor will change to `not-allowed` to match the behavior of checkbox and radio buttons in v2.0.8+ of this repo. Demo updated to reflect the same. Cheers.
