### ISSUE TITLE
Checkbox styles change on browser zoom in or zoom out (Chrome)

### ISSUE THREAD

**Issue by sandeeppbajaj** [PredixDev/px-forms-design#13]
# Submit an Issue

Hi,

## Expected behavior and actual behavior:
Checkboxes should resize without losing styles when browser window zoom in or zoom out is preformed

## Steps to reproduce the problem:
1. Open https://www.predix-ui.com/#/css/visual/px-forms-design
2. Switch to Basic Form Tab
3. Zoom-in or Zoom-out on the browser window
4. Observe the style change on check-box

## Environment:
Machine: Mac
Browser: Chrome
Version: 2.0.8

## Screenshots :
<img width="394" alt="screen shot 2018-02-21 at 11 37 54 am" src="https://user-images.githubusercontent.com/6015773/36501365-c7eea8cc-16fb-11e8-91d0-d46930f1be94.png">

<img width="452" alt="screen shot 2018-02-21 at 11 38 03 am" src="https://user-images.githubusercontent.com/6015773/36501375-cd341308-16fb-11e8-826d-30ed2b706b18.png">

**Comment by randyaskin** [comment]
Seems to be a reported issue / intended behavior in Chrome.
`This is an expected behavior.  There are no ways to draw the native appearance in non-100% zoomed size. So we draw fallback appearance.`
https://bugs.chromium.org/p/chromium/issues/detail?id=288586

Also found some results on Google / Stack Overflow, but at first glance this doesn't seem to have anything to do with us, as we're just using regular HTML5 checkboxes.
